

frankdevhub: 
  secret: ${random.value}
  number: ${random.int}
  name: www.frankdevhub.com
  desc: ${frankdevhub.name} is a domain name

server: 
    port: 8090
  

spring: 
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing